### ISSUE TITLE
drop down for save location

### ISSUE THREAD

**Issue by felon-efnet** [rajeshca911/Save-Transfer-Wizard#1]
drop down for save location when trying to retrieve PS5 save games doesn't function properly. I will try the app on my PS4 Pro just to verify its functioning correctly. thank you

**Comment by rajeshca911** [comment]
hey. the tool is working fine
https://www.mediafire.com/file/fiar094hk1efuju/savetransfer.mp4/file
please see the attached video. 
you must enable ftp before using it, (persistent ftp advised since it works after closing the web browse as well)

**Comment by felon-efnet** [comment]
thanks, sorry about that, pulled my saves off. thanks so much for your work!
